name: "Podcast generator v1.0"
author: "Mukesh"
description: "Generates a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "DockerFile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: "comitters email"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Committers name"
    required: true
    default: ${{ github.actor }}
    
